/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cams_assignment;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author nbros
 */
public class InsertAppointment extends javax.swing.JFrame {

    /**
     * Creates new form InsertAppointment
     */
    Admin a = new Admin();
    public InsertAppointment() {
        initComponents();
    }
    public InsertAppointment(Admin a) {
        initComponents();
        this.a = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        timebuttonGroup = new javax.swing.ButtonGroup();
        TitleLabel = new javax.swing.JLabel();
        NLabel = new javax.swing.JLabel();
        HPLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        NTextField = new javax.swing.JTextField();
        HPTextField = new javax.swing.JTextField();
        FirstRadioButton = new javax.swing.JRadioButton();
        ThirdRadioButton = new javax.swing.JRadioButton();
        SecondRadioButton = new javax.swing.JRadioButton();
        DateChooser = new com.toedter.calendar.JDateChooser();
        InsertButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insert_Appoitment_page");

        TitleLabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        TitleLabel.setText("Insert Appointment");

        NLabel.setText("Name :");

        HPLabel.setText("Contact number :");

        DateLabel.setText("Date :");

        TimeLabel.setText("Time :");

        timebuttonGroup.add(FirstRadioButton);
        FirstRadioButton.setText("10.00 a.m. - 12.00 p.m.");

        timebuttonGroup.add(ThirdRadioButton);
        ThirdRadioButton.setText("4.00 p.m. - 6.00 p.m.");

        timebuttonGroup.add(SecondRadioButton);
        SecondRadioButton.setText("1.00p.m. - 3.00p.m.");

        InsertButton.setText("Insert");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HPLabel)
                            .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NTextField)
                            .addComponent(HPTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(FirstRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ThirdRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SecondRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TitleLabel)))
                .addGap(111, 111, 111))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(InsertButton)
                        .addGap(217, 217, 217))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackButton)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NLabel)
                    .addComponent(NTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HPLabel)
                    .addComponent(HPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateLabel)
                    .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeLabel)
                    .addComponent(FirstRadioButton))
                .addGap(18, 18, 18)
                .addComponent(SecondRadioButton)
                .addGap(18, 18, 18)
                .addComponent(ThirdRadioButton)
                .addGap(30, 30, 30)
                .addComponent(InsertButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        try{
            SimpleDateFormat DateFormat = new SimpleDateFormat("dd-MM-yyyy");
            String time = "";
            if(FirstRadioButton.isSelected()){
                time = "10.00 a.m.-12.00 p.m.";
            }else if(SecondRadioButton.isSelected()){
                time = "1.00 p.m.-3.00 p.m.";
            }else{
                time = "4.00 p.m.-6.00 p.m.";
            }
            String Name = NTextField.getText();
            String Contact = HPTextField.getText();
            Date SelectedDate = DateChooser.getDate();
            String Date = DateFormat.format(SelectedDate);
            String Time = time;
            DBFile db = new DBFile();
            if(Name.equals("")){
                 JOptionPane.showMessageDialog(null, "Please insert the Name !");
            }else if(Contact.equals("")){
                 JOptionPane.showMessageDialog(null, "Please insert tht Contact Number !");
            }else if(!db.CheckContact(Contact)){
                 JOptionPane.showMessageDialog(null, "Wrong Phone Numebr Format !");
            }else if(Time.equals("")){
                JOptionPane.showMessageDialog(null, "Please select the time slot !");
            }else if (!db.CheckAppointmentAvailable(Date, Time)){
                JOptionPane.showMessageDialog(null, "The Date of the time slot is fully booked !");
            }else if(!db.CheckDateValid(SelectedDate)){
                JOptionPane.showMessageDialog(null, "The Appointment can only be booked one day before !");
            }else{
                JOptionPane.showMessageDialog(null, "insert Successful !");
                a.InsertAppointment(Name, Contact, Date, Time);
                AdminAppointmentPage aap = new AdminAppointmentPage(a);
                aap.setVisible(true);
                this.dispose();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please fill the information !");
        }
    }//GEN-LAST:event_InsertButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        AdminAppointmentPage aap = new AdminAppointmentPage(a);
        aap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JRadioButton FirstRadioButton;
    private javax.swing.JLabel HPLabel;
    private javax.swing.JTextField HPTextField;
    private javax.swing.JButton InsertButton;
    private javax.swing.JLabel NLabel;
    private javax.swing.JTextField NTextField;
    private javax.swing.JRadioButton SecondRadioButton;
    private javax.swing.JRadioButton ThirdRadioButton;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField jTextField3;
    private javax.swing.ButtonGroup timebuttonGroup;
    // End of variables declaration//GEN-END:variables
}
